### ISSUE TITLE
No rule to make clang tidy

### ISSUE THREAD

**Issue by hamishwillee** [Auterion/mavlink-testing-suite#20]
I just ran the [Fix formatting and style instructions](https://github.com/Auterion/mavlink-testing-suite#fix-code-formatting-and-style):
```
~/mavlink-testing-suite$ (cd build && make format; make clang_tidy)
make: *** No rule to make target 'format'.  Stop.
make: *** No rule to make target 'clang_tidy'.  Stop.
ubuntu@ubuntu:~/mavlink-testing-suite$ 
```
I presume I am missing dependencies, but what are they?

This is on Ubuntu 16.04, with current PX4 firmware, SDK dependencies, and master from this repo. The repo builds.

**Comment by julianoes** [comment]
I'm assuming you need to build first, can you try to do this before:
```
(mkdir -p build && cd build && cmake .. && make)
```

**Comment by hamishwillee** [comment]
@julianoes 

Nope, same error:
```
ubuntu@ubuntu:~/github/mavlink-testing-suite$ (cd build && make format; make clang_tidy)
make: *** No rule to make target 'format'.  Stop.
make: *** No rule to make target 'clang_tidy'.  Stop.
```
Note that I just installed the [SDK dependencies for Linux](https://sdk.dronecode.org/en/contributing/build.html#build_cpp_linux), so did nothing special to get clang.

**Comment by julianoes** [comment]
Works for me. Can you try with `export VERBOSE=1`?

**Comment by hamishwillee** [comment]
Yes, then I get no output at all.

**Comment by julianoes** [comment]
> Note that I just installed the SDK dependencies for Linux, so did nothing special to get clang.

Good point. The make targets don't exist if the tools are not installed:
https://github.com/Auterion/mavlink-testing-suite/blob/3ece615f1ad877fd030dbd8a635a6115622d47f4/CMakeLists.txt#L60-L89

It's a bit unfortunate. We either have to warn if the tools are not installed, or we have to always show the targets and then fail with the appropriate warning if the tools are not installed.
