### ISSUE TITLE
Build issues with mission.cpp and param.cpp, differences with run_ci.sh and instructions

### ISSUE THREAD

**Issue by bminerd** [Auterion/mavlink-testing-suite#6]
Running into issues building via the README instructions. Below is the make error:
```
In file included from /home/osboxes/mavlink-testing-suite/src/tests/mission.cpp:2:0:
/home/osboxes/mavlink-testing-suite/src/tests/mission.h:6:51: fatal error: dronecode_sdk/plugins/mission/mission.h: No such file or directory
compilation terminated.
CMakeFiles/mavlink_testing_suite.dir/build.make:110: recipe for target 'CMakeFiles/mavlink_testing_suite.dir/src/tests/mission.cpp.o' failed
make[2]: *** [CMakeFiles/mavlink_testing_suite.dir/src/tests/mission.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mavlink_testing_suite.dir/all' failed
make[1]: *** [CMakeFiles/mavlink_testing_suite.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
I was able to fix this issue by updating the #include in src/tests/mission.h to point to <dronecode_sdk/mission.h>. The same issue exists for src/tests/param.h.

Unclear why this passes in Travis CI, however I did notice that the DronecodeSDK install relative paths are different in the run_ci.sh script:
```
SDK_INSTALL_DIR="$(pwd)/DronecodeSDK-install"

set -e

# Get the SDK - for now we use the latest develop version
if [ -d DronecodeSDK ]; then
	# If it's already here, make sure it's up-to-date and clean
	pushd DronecodeSDK
	git pull
	make clean
	popd
else
	git clone --recursive https://github.com/Dronecode/DronecodeSDK.git || true
fi
pushd DronecodeSDK
[ ! -d "$SDK_INSTALL_DIR" ] && mkdir -p "$SDK_INSTALL_DIR"
export INSTALL_PREFIX="$SDK_INSTALL_DIR"
make default install
popd
```
The variable $(pwd) gets evaluated when SDK_INSTALL_DIR is defined at the top of the script, but is used from a different sub-directory with the expectation (I believe) that it will be reevaluated based on the current directory/pwd at that point. This creates a different relative path structure on the Travis CI server than the manual instructions.

Let me know if I can provide anything else that's helpful. This might make sense as two separate issues, but it's possible that fixing the source files breaks CI and are therefore interdependent.
@julianoes

**Comment by julianoes** [comment]
Hi @bminerd !

Have you tried pulling the latest DronecodeSDK (develop branch as by default)? And then done the `make default install` again?

**Comment by bminerd** [comment]
Oops, looks like I must've had an old version. Files are in the right place now, thanks!

**Comment by julianoes** [comment]
Ok I'm glad. I will address this by pulling the Dronecode SDK in automatically as part of the build instead of the manual steps which should prevent this situation in the future.
